#####
name: Eva_SynMSE
port: 8097   #  port parameters for visdom

save_root: '/opt/data/private/SynMSE-main/output/Eva/'
epoch: 1        # starting epoch
n_epochs: 500      # How often do you want to display output images during training
batchSize: 1               # size of the batches
dataroot: '/opt/data/private/dataset/clinic_mix/'  # root directory of the train dataset

lr: 0.0001               # initial learning rate
size: [32, 256, 384]       # D H W
depth: 32    # D
input_nc: 2         
output_nc: 1                  
cuda: True                
n_cpu: 7
loss: 'L1'
# affine
rotation: 3        # range of rotation if use affine
translation: 0.08    # range of translation if use affine
scaling: 0.08      # range of scaling if use affine
# non affine
non_affine_alpha: 150
gaussian_smoothing: 12